# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"



    filter_sets:
        squared_thumbnail_medium:
              quality: 100
              filters:
                  thumbnail:
                      size: [300,300]
                      mode: outbound
                      allow_upscale: true

        squared_thumbnail_small:
              filters:
                  thumbnail:
                      size: [200,200]
                      mode: outbound
                      allow_upscale: true

        squared_thumbnail_big:
              filters:
                  thumbnail:
                      size: [800,800]
                      mode: outbound
                      allow_upscale: true


        squared_thumbnail_min:
              filters:
                  thumbnail:
                      size: [100,100]
                      mode: outbound
                      allow_upscale: true


        squared_thumbnail_article_view:
              filters:
                  thumbnail:
                      size: [900,900]
                      mode: outbound
                      allow_upscale: true

        squared_thumbnail_brand:
              filters:
                  thumbnail:
                      size: [600,400]
                      mode: outbound
                      allow_upscale: true
       