vich_uploader:
    db_driver: orm

    mappings:
            carousel_image:
                uri_prefix: /uploads/carousels
                upload_destination: '%kernel.project_dir%/public/uploads/carousels'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                delete_on_update: true
                delete_on_remove: true

            user_image:
                uri_prefix: /uploads/users
                upload_destination: '%kernel.project_dir%/public/uploads/users'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                delete_on_update: true
                delete_on_remove: true


            article_image:
                uri_prefix: /uploads/articles
                upload_destination: '%kernel.project_dir%/public/uploads/articles'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                delete_on_update: true
                delete_on_remove: true



