vich_uploader:
    db_driver: orm

    mappings:
        carousel_image:
            uri_prefix: /uploads/carousels
            upload_destination: '%kernel.project_dir%/public/uploads/carousels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
